language: python
dist: xenial
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
env:
  - MC_VERSION=1.14
before_install:
  - wget https://raw.githubusercontent.com/python-pillow/Pillow/master/src/libImaging/Imaging.h
  - wget https://raw.githubusercontent.com/python-pillow/Pillow/master/src/libImaging/ImagingUtils.h
  - wget https://raw.githubusercontent.com/python-pillow/Pillow/master/src/libImaging/ImPlatform.h
install:
  - pip install -q pillow
  - pip install -q numpy
  - pip install -q networkx
  - pip install -q pytest
  - python3 setup.py build
  - sudo apt update
  - sudo apt install nodejs npm -y
  - npm install -g netlify-cli
before_script:
  - git clone git://github.com/Bartixxx32/Minecraft-Overviewer-Addons.git ~/mcoa/
  - mkdir -p ~/.minecraft/versions/${MC_VERSION}/
  - wget -N https://overviewer.org/textures/${MC_VERSION} -O ~/.minecraft/versions/${MC_VERSION}/${MC_VERSION}.jar
script:
  - pytest
  - python3 overviewer.py ~/mcoa/exmaple ~/test-output --rendermodes=smooth-lighting -p1
  - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
notifications:
  email: false
